acceleration:
  threshold: 0.047
  min_speed: 20
  min_duration: 0.5
  max_gap: 3

deceleration:
  dec_threshold: 0.466
  min_speed: 20
  min_duration: 0.5
  max_gap: 3

cornering:
  accy_threshold: 0.18
  min_speed: 20
  min_duration: 0.6
  max_gap: 3

speeding:
  speed_limit: 40
  min_duration: 3
  max_gap: 5

phone_usage:
  min_duration: 3
  max_gap: 20


weights:
  speeding_weight: 0.20
  phone_usage_weight: 0.20
  acceleration_weight: 0.20
  cornering_weight: 0.20
  braking_weight: 0.20

database:
  sqlite_path: "D:/Downloadss/New_db/test.db"

model_path: models/driving_model.pkl
target_column: safety_score
numerical_features:
  - acceleration_x_original
  - acceleration_y_original
  - acceleration_z_original
  - acceleration
  - deceleration
  - midSpeed

