version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DB_PATH=${DB_PATH}
      - MODEL_PATH=${MODEL_PATH}
      - BACKUP_PATH=${BACKUP_PATH}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./model_backups:/app/model_backups    # <<< mount backup dir
    command: >
      uvicorn main:app
      --host 0.0.0.0 --port ${PORT:-8000} --reload

